### PR TITLE
add a Person

### PR DESCRIPTION
**Pull request by AlexandreAssmus**
Add a Person with on wrong fact

### CODE REVIEW

**Comment by Javanochka** [comment]
Please, resolve your merge conflict.

**Comment by Javanochka** [comment]
Good work!

**Comment by AlexandreAssmus** [comment]
Hello, when i try the step 5 of your tutorial "Apply the updates to the main branch" I have this error : 
$ git pull upstream main
From github.com:Javanochka/m1-data-science-td
 * branch            main       -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        class01-git/facts.py
Please commit your changes or stash them before you merge.
Aborting
Merge with strategy ort failed.


Is it normal or is there a way to fix it ?

**Comment by AlexandreAssmus** [comment]
Thanks for your response. Actually at the step 4 I have this error :
$ git fetch upstream
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

But i created a ssh key during the course on monday, so i don't really know how to fix the problem. After some research i try this command :
ssh-add -l -E sha256
The agent has no identities.

Do you have any idea how to solve this problem ?

**Pull request closed without merging**
